/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.distributorController;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus TUF
 */
public class DistributorForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DistributorForm.class.getName());
    private final distributorController controller;
    private final String idDistributor;

    public DistributorForm(String idDistributor, distributorController controller) {
        initComponents();
        this.pack(); 
        this.setLocationRelativeTo(null); 
        this.setResizable(false);
        this.controller = controller;        
        this.idDistributor = idDistributor;
        System.out.println("[DEBUG] DistributorForm dibuka untuk ID: " + idDistributor);

    java.net.URL imgURL = getClass().getResource("/DistributorBg.png");
    if (imgURL != null) {
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
        java.awt.Image img = icon.getImage().getScaledInstance(
            800, 
            500, 
            java.awt.Image.SCALE_SMOOTH
        );
        lblDistributorBg.setIcon(new javax.swing.ImageIcon(img));
    } else {
        System.err.println("Gambar tidak ditemukan di /resources/DistributorBg.png");
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtWilayahPasar = new javax.swing.JTextField();
        lblWilayahPasar = new javax.swing.JLabel();
        txtNamaUsaha = new javax.swing.JTextField();
        lblNamaUsaha = new javax.swing.JLabel();
        txtNoTelp = new javax.swing.JTextField();
        lblNoTelp = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        lblDistributorBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        txtWilayahPasar.setColumns(15);
        txtWilayahPasar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWilayahPasarActionPerformed(evt);
            }
        });
        jPanel1.add(txtWilayahPasar);
        txtWilayahPasar.setBounds(430, 280, 278, 34);

        lblWilayahPasar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblWilayahPasar.setForeground(new java.awt.Color(255, 255, 255));
        lblWilayahPasar.setText("Wilayah Pasar");
        jPanel1.add(lblWilayahPasar);
        lblWilayahPasar.setBounds(430, 250, 110, 20);

        txtNamaUsaha.setColumns(15);
        txtNamaUsaha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaUsahaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNamaUsaha);
        txtNamaUsaha.setBounds(430, 200, 278, 34);

        lblNamaUsaha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNamaUsaha.setForeground(new java.awt.Color(255, 255, 255));
        lblNamaUsaha.setText("Nama Usaha");
        jPanel1.add(lblNamaUsaha);
        lblNamaUsaha.setBounds(430, 170, 100, 20);

        txtNoTelp.setColumns(15);
        txtNoTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoTelpActionPerformed(evt);
            }
        });
        jPanel1.add(txtNoTelp);
        txtNoTelp.setBounds(430, 120, 278, 34);

        lblNoTelp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNoTelp.setForeground(new java.awt.Color(255, 255, 255));
        lblNoTelp.setText("No. Telp");
        jPanel1.add(lblNoTelp);
        lblNoTelp.setBounds(430, 90, 70, 20);

        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(0, 102, 0));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali);
        btnKembali.setBounds(460, 340, 100, 30);

        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(0, 102, 0));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimpan);
        btnSimpan.setBounds(570, 340, 100, 30);

        lblDistributorBg.setText("jLabel1");
        jPanel1.add(lblDistributorBg);
        lblDistributorBg.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoTelpActionPerformed

    private void txtNamaUsahaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaUsahaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaUsahaActionPerformed

    private void txtWilayahPasarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWilayahPasarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWilayahPasarActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String noTelp = txtNoTelp.getText().trim();
    String namaUsaha = txtNamaUsaha.getText().trim();
    String wilayahPasar = txtWilayahPasar.getText().trim();

    Controller.distributorController controller = new Controller.distributorController();
    boolean success = controller.updateDataDistributor(idDistributor, noTelp, namaUsaha, wilayahPasar);
    if (success) {
        JOptionPane.showMessageDialog(this, "Data distributor berhasil disimpan!");
        new LoginForm().setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan data distributor! Pastikan semua input sudah benar.",
                "Error", JOptionPane.ERROR_MESSAGE);
    }
       // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        new RegisterForm().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDistributorBg;
    private javax.swing.JLabel lblNamaUsaha;
    private javax.swing.JLabel lblNoTelp;
    private javax.swing.JLabel lblWilayahPasar;
    private javax.swing.JTextField txtNamaUsaha;
    private javax.swing.JTextField txtNoTelp;
    private javax.swing.JTextField txtWilayahPasar;
    // End of variables declaration//GEN-END:variables
}
