/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.hasilPanenController;
import Model.hasilPanen;
import Session.UserSession;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus TUF
 */
public class HasilPanenForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HasilPanenForm.class.getName());

    /**
     * Creates new form HasilPanenForm
     */
    
    private final hasilPanenController controller = new hasilPanenController();;
    private final String idUser = UserSession.getIdUser();
    
    public HasilPanenForm() {
        initComponents();
        this.pack(); 
        this.setLocationRelativeTo(null); 
        this.setResizable(false);
    java.net.URL imgURL = getClass().getResource("/HasilPanenBg.png");
    if (imgURL != null) {
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
        java.awt.Image img = icon.getImage().getScaledInstance(
            800, 
            500, 
            java.awt.Image.SCALE_SMOOTH
        );
        lblHasilPanenBg.setIcon(new javax.swing.ImageIcon(img));
    } else {
        System.err.println(" Gambar tidak ditemukan di /resources/HasilPanenBg.png");
        }
        loadTabelPanen();
    }
    private void loadTabelPanen() {
            List<hasilPanen> daftar = controller.getPanenByPetani(idUser);

            DefaultTableModel model = new DefaultTableModel(
                new Object[]{"ID Panen", "Jumlah (Kg)", "Stok Gudang", "Tanggal Panen"}, 0
            );

            for (hasilPanen h : daftar) {
                model.addRow(new Object[]{
                    h.getIdPanen(),
                    h.getJumlahPanen(),
                    h.getStokGudang(),
                    h.getTanggalPanen()
                });
            }

            tblHasilPanen.setModel(model);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSatuan = new javax.swing.JLabel();
        lblJumlah = new javax.swing.JLabel();
        cmbSatuan = new javax.swing.JComboBox<>();
        btnTambah = new javax.swing.JButton();
        btnPerbarui = new javax.swing.JButton();
        txtJumlah = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHasilPanen = new javax.swing.JTable();
        btnKembali = new javax.swing.JButton();
        lblHasilPanenBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        lblSatuan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSatuan.setForeground(new java.awt.Color(0, 102, 0));
        lblSatuan.setText("Satuan");
        jPanel1.add(lblSatuan);
        lblSatuan.setBounds(440, 140, 100, 20);

        lblJumlah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJumlah.setForeground(new java.awt.Color(0, 102, 0));
        lblJumlah.setText("Jumlah Hasil Panen");
        jPanel1.add(lblJumlah);
        lblJumlah.setBounds(110, 140, 210, 20);

        cmbSatuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kg", "Ton" }));
        jPanel1.add(cmbSatuan);
        cmbSatuan.setBounds(440, 160, 90, 40);

        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(0, 102, 0));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambah);
        btnTambah.setBounds(560, 160, 90, 40);

        btnPerbarui.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPerbarui.setForeground(new java.awt.Color(0, 102, 0));
        btnPerbarui.setText("Perbarui");
        btnPerbarui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerbaruiActionPerformed(evt);
            }
        });
        jPanel1.add(btnPerbarui);
        btnPerbarui.setBounds(80, 410, 100, 30);

        txtJumlah.setColumns(15);
        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });
        jPanel1.add(txtJumlah);
        txtJumlah.setBounds(110, 160, 290, 40);

        tblHasilPanen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id_panen", "jumlah_panen", "stok_gudang", "satuan", "tanggal_panen", "id_petani", "id_admin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHasilPanen);
        if (tblHasilPanen.getColumnModel().getColumnCount() > 0) {
            tblHasilPanen.getColumnModel().getColumn(0).setResizable(false);
            tblHasilPanen.getColumnModel().getColumn(1).setResizable(false);
            tblHasilPanen.getColumnModel().getColumn(2).setResizable(false);
            tblHasilPanen.getColumnModel().getColumn(3).setResizable(false);
            tblHasilPanen.getColumnModel().getColumn(4).setResizable(false);
            tblHasilPanen.getColumnModel().getColumn(5).setResizable(false);
            tblHasilPanen.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(80, 290, 640, 120);

        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(0, 102, 0));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali);
        btnKembali.setBounds(660, 40, 90, 40);

        lblHasilPanenBg.setText("jLabel2");
        jPanel1.add(lblHasilPanenBg);
        lblHasilPanenBg.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPerbaruiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerbaruiActionPerformed
    try {
        loadTabelPanen(); 
        JOptionPane.showMessageDialog(this, "Tabel berhasil diperbarui!", "Info", JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memperbarui tabel: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }    
    }//GEN-LAST:event_btnPerbaruiActionPerformed

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
       try {
        double jumlah = Double.parseDouble(txtJumlah.getText());
        String satuan = cmbSatuan.getSelectedItem().toString();

        boolean success = controller.tambahPanen(idUser, jumlah, satuan);

        if (success) {
            JOptionPane.showMessageDialog(this, "Data panen berhasil ditambahkan!");
            txtJumlah.setText("");
            loadTabelPanen();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menambah data panen!", "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Masukkan jumlah panen yang valid!", "Input Error", JOptionPane.WARNING_MESSAGE);
}

    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        MenuPetani petani = new MenuPetani();
        petani.setVisible(true);
        this.dispose();             
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HasilPanenForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnPerbarui;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cmbSatuan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHasilPanenBg;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JLabel lblSatuan;
    private javax.swing.JTable tblHasilPanen;
    private javax.swing.JTextField txtJumlah;
    // End of variables declaration//GEN-END:variables
}
