

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author Asus TUF
 */
public class InfoPetaniDistributorForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InfoPetaniDistributorForm.class.getName());
    private final Controller.petaniController petaniCtrl = new Controller.petaniController();

    /**
     * Creates new form InfoPetaniDistributorForm
     */
    public InfoPetaniDistributorForm() {
        initComponents();
        this.pack(); 
        this.setLocationRelativeTo(null); 
        this.setResizable(false);
        
        loadDataPetani(false);
        btnCari.addActionListener(evt -> loadDataPetani(true));
        txtLokasi.addKeyListener(new java.awt.event.KeyAdapter() {
    @Override
    public void keyReleased(java.awt.event.KeyEvent e) {
        loadDataPetani(false);
    }
});

    java.net.URL imgURL = getClass().getResource("/InfoPetaniBg.png");
    if (imgURL != null) {
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
        java.awt.Image img = icon.getImage().getScaledInstance(
            800, 
            500, 
            java.awt.Image.SCALE_SMOOTH
        );
        lblInfoPetaniBg.setIcon(new javax.swing.ImageIcon(img));
    } else {
        System.err.println("Gambar tidak ditemukan di /resources/InfoPetaniBg.png");
        }
    }
private boolean loadDataPetani(boolean showMessageIfEmpty) {
    String lokasi = txtLokasi.getText().trim();
    String sortOrder = cmbJumlahPanen.getSelectedIndex() == 0 ? "DESC" : "ASC";

    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No");
    model.addColumn("Nama Petani");
    model.addColumn("No. Telp");
    model.addColumn("Nama Sawah");
    model.addColumn("Lokasi");
    model.addColumn("Stok Gudang");
    model.addColumn("Tanggal Panen Terakhir");

    List<Object[]> data = petaniCtrl.getInfoPetani(lokasi, sortOrder);

    if (data.isEmpty()) {
        tblPetani.setModel(model); 
        if (showMessageIfEmpty) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Lokasi tidak ditemukan.",
                "Tidak Ada Data",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
            );
        }
        return false;
    }

    int no = 1;
    for (Object[] row : data) {
        model.addRow(new Object[]{
            no++, row[0], row[1], row[2], row[3], row[4], row[5]
        });
    }

    tblPetani.setModel(model);
    tblPetani.revalidate();
    tblPetani.repaint();
    return true;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblJumlah = new javax.swing.JLabel();
        txtLokasi = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();
        cmbJumlahPanen = new javax.swing.JComboBox<>();
        btnCari = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPetani = new javax.swing.JTable();
        lblLokasi = new javax.swing.JLabel();
        lblInfoPetaniBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        lblJumlah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJumlah.setForeground(new java.awt.Color(255, 255, 255));
        lblJumlah.setText("Stok Gudang Petani");
        jPanel1.add(lblJumlah);
        lblJumlah.setBounds(430, 130, 170, 20);

        txtLokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLokasiActionPerformed(evt);
            }
        });
        jPanel1.add(txtLokasi);
        txtLokasi.setBounds(70, 150, 254, 40);

        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(0, 102, 0));
        btnKembali.setText("Kembali");
        btnKembali.setToolTipText("");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali);
        btnKembali.setBounds(660, 40, 90, 40);

        cmbJumlahPanen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbJumlahPanen.setForeground(new java.awt.Color(0, 102, 0));
        cmbJumlahPanen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tertinggi ke Terendah", "Terendah ke Tertinggi" }));
        cmbJumlahPanen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJumlahPanenActionPerformed(evt);
            }
        });
        jPanel1.add(cmbJumlahPanen);
        cmbJumlahPanen.setBounds(430, 150, 310, 40);

        btnCari.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCari.setForeground(new java.awt.Color(0, 102, 0));
        btnCari.setText("Cari");
        btnCari.setToolTipText("");
        jPanel1.add(btnCari);
        btnCari.setBounds(330, 150, 76, 40);

        tblPetani.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id_petani", "nama_lengkap", "username", "no_telp", "nama_sawah", "lokasi", "luas_lahan", "role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblPetani);
        if (tblPetani.getColumnModel().getColumnCount() > 0) {
            tblPetani.getColumnModel().getColumn(0).setResizable(false);
            tblPetani.getColumnModel().getColumn(1).setResizable(false);
            tblPetani.getColumnModel().getColumn(2).setResizable(false);
            tblPetani.getColumnModel().getColumn(3).setResizable(false);
            tblPetani.getColumnModel().getColumn(4).setResizable(false);
            tblPetani.getColumnModel().getColumn(5).setResizable(false);
            tblPetani.getColumnModel().getColumn(6).setResizable(false);
            tblPetani.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(80, 240, 650, 150);

        lblLokasi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLokasi.setForeground(new java.awt.Color(255, 255, 255));
        lblLokasi.setText("Berdasarkan Lokasi");
        jPanel1.add(lblLokasi);
        lblLokasi.setBounds(70, 130, 170, 20);

        lblInfoPetaniBg.setText("jLabel1");
        jPanel1.add(lblInfoPetaniBg);
        lblInfoPetaniBg.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        new MenuDistributor().setVisible(true);
        // Tutup halaman dashboard sekarang
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void txtLokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLokasiActionPerformed
         loadDataPetani(false);
    }//GEN-LAST:event_txtLokasiActionPerformed

    private void cmbJumlahPanenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJumlahPanenActionPerformed
        loadDataPetani(false);// TODO add your handling code here:
    }//GEN-LAST:event_cmbJumlahPanenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new InfoPetaniDistributorForm().setVisible(true));
    
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnKembali;
    private javax.swing.JComboBox<String> cmbJumlahPanen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblInfoPetaniBg;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JLabel lblLokasi;
    private javax.swing.JTable tblPetani;
    private javax.swing.JTextField txtLokasi;
    // End of variables declaration//GEN-END:variables
}
