/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Asus TUF
 */
import Controller.distributorController;
import Model.Distributor;
import java.util.List;
import javax.swing.JOptionPane;

public class KelolaAkunDistributor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KelolaAkunDistributor.class.getName());
    private final distributorController controller = new distributorController();

    public KelolaAkunDistributor() {
    initComponents();
    this.pack(); 
    this.setLocationRelativeTo(null); 
    this.setResizable(false);
    loadTabelDistributor();
    
    java.net.URL imgURL = getClass().getResource("/KelolaAkunBg.png");
    if (imgURL != null) {
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
        java.awt.Image img = icon.getImage().getScaledInstance(
            800, 
            500,
            java.awt.Image.SCALE_SMOOTH
        );
        lblKelolaAkunDistributorBg.setIcon(new javax.swing.ImageIcon(img));
    } else {
        System.err.println("Gambar tidak ditemukan di /resources/KelolaAkunBg.png");
    }
    }
    private void loadTabelDistributor() {
        List<Distributor> list = controller.getAllDistributor();
        javax.swing.table.DefaultTableModel model = 
        (javax.swing.table.DefaultTableModel) tblDistributor.getModel();
        model.setRowCount(0);
        
        for (Distributor d : list) {
            model.addRow(new Object[]{
                d.getIdDistributor(),
                d.getNamaLengkap(),
                d.getUsername(),
                d.getPassword(),
                d.getNoTelp(),
                d.getNamaUsaha(),
                d.getWilayahPasar(),
                d.getRole()
            });
        }
    }

    private void clearForm() {
        txtNama.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        txtJumlah.setText("");
        txtNamaUsaha.setText("");
        txtWilayahPasar.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPassword = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblJumlah = new javax.swing.JLabel();
        lblNamaUsaha = new javax.swing.JLabel();
        lblWilayahPasar = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        txtWilayahPasar = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        txtNamaUsaha = new javax.swing.JTextField();
        btnHapus = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDistributor = new javax.swing.JTable();
        btnKembali = new javax.swing.JButton();
        btnPerbarui = new javax.swing.JButton();
        lblKelolaAkunDistributorBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");
        jPanel1.add(lblPassword);
        lblPassword.setBounds(90, 190, 180, 20);

        lblNama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNama.setForeground(new java.awt.Color(255, 255, 255));
        lblNama.setText("Nama Distributor");
        jPanel1.add(lblNama);
        lblNama.setBounds(90, 70, 180, 20);

        lblJumlah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJumlah.setForeground(new java.awt.Color(255, 255, 255));
        lblJumlah.setText("No telepon");
        jPanel1.add(lblJumlah);
        lblJumlah.setBounds(420, 70, 240, 20);

        lblNamaUsaha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNamaUsaha.setForeground(new java.awt.Color(255, 255, 255));
        lblNamaUsaha.setText("Nama Usaha");
        jPanel1.add(lblNamaUsaha);
        lblNamaUsaha.setBounds(420, 130, 180, 20);

        lblWilayahPasar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblWilayahPasar.setForeground(new java.awt.Color(255, 255, 255));
        lblWilayahPasar.setText("Wilayah Pasar");
        jPanel1.add(lblWilayahPasar);
        lblWilayahPasar.setBounds(420, 190, 180, 20);

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username");
        jPanel1.add(lblUsername);
        lblUsername.setBounds(90, 130, 180, 20);
        jPanel1.add(txtPassword);
        txtPassword.setBounds(90, 210, 270, 30);
        jPanel1.add(txtWilayahPasar);
        txtWilayahPasar.setBounds(420, 210, 270, 30);
        jPanel1.add(txtUsername);
        txtUsername.setBounds(90, 150, 270, 30);
        jPanel1.add(txtNama);
        txtNama.setBounds(90, 90, 270, 30);
        jPanel1.add(txtJumlah);
        txtJumlah.setBounds(420, 90, 270, 30);
        jPanel1.add(txtNamaUsaha);
        txtNamaUsaha.setBounds(420, 150, 270, 30);

        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(0, 102, 0));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus);
        btnHapus.setBounds(470, 250, 100, 30);

        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(0, 102, 0));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambah);
        btnTambah.setBounds(230, 250, 100, 30);

        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(0, 102, 0));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit);
        btnEdit.setBounds(350, 250, 100, 30);

        tblDistributor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id_distributor", "nama_lengkap", "username", "password", "no_telp", "nama_usaha", "wilayah_pasar", "role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDistributor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDistributorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDistributor);
        if (tblDistributor.getColumnModel().getColumnCount() > 0) {
            tblDistributor.getColumnModel().getColumn(0).setResizable(false);
            tblDistributor.getColumnModel().getColumn(1).setResizable(false);
            tblDistributor.getColumnModel().getColumn(2).setResizable(false);
            tblDistributor.getColumnModel().getColumn(3).setResizable(false);
            tblDistributor.getColumnModel().getColumn(4).setResizable(false);
            tblDistributor.getColumnModel().getColumn(5).setResizable(false);
            tblDistributor.getColumnModel().getColumn(6).setResizable(false);
            tblDistributor.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 310, 660, 140);

        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(0, 102, 0));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali);
        btnKembali.setBounds(640, 20, 100, 30);

        btnPerbarui.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPerbarui.setForeground(new java.awt.Color(0, 102, 0));
        btnPerbarui.setText("Perbarui");
        btnPerbarui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerbaruiActionPerformed(evt);
            }
        });
        jPanel1.add(btnPerbarui);
        btnPerbarui.setBounds(70, 450, 100, 30);

        lblKelolaAkunDistributorBg.setText("jLabel1");
        jPanel1.add(lblKelolaAkunDistributorBg);
        lblKelolaAkunDistributorBg.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
    boolean success = controller.tambahDistributor(
        txtNama.getText(),
        txtUsername.getText(),
        txtPassword.getText(),
        txtJumlah.getText(),
        txtNamaUsaha.getText(),
        txtWilayahPasar.getText()
    );

    if (success) {
        JOptionPane.showMessageDialog(this, "Data distributor berhasil ditambahkan!");
        loadTabelDistributor();
        clearForm();
    } else {
        JOptionPane.showMessageDialog(this, "Gagal menambah distributor. Cek input atau username sudah terdaftar.");
    }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
    int selectedRow = tblDistributor.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data yang mau diubah!");
        return;
    }
    String id = tblDistributor.getValueAt(selectedRow, 0).toString();
    String telp = txtJumlah.getText();
    String usaha = txtNamaUsaha.getText();
    String pasar = txtWilayahPasar.getText();

    if (controller.updateDataDistributor(id, telp, usaha, pasar)) {
        JOptionPane.showMessageDialog(this, "Data distributor diperbarui!");
        loadTabelDistributor();
        clearForm();
    } else {
        JOptionPane.showMessageDialog(this, "Gagal memperbarui data distributor!");
    }     
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
    int selectedRow = tblDistributor.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data yang mau dihapus!");
        return;
    }
    String id = tblDistributor.getValueAt(selectedRow, 0).toString();

    if (controller.deleteDistributor(id)) {
        JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
        loadTabelDistributor();
        clearForm();
    } else {
        JOptionPane.showMessageDialog(this, "Gagal menghapus data!");
    } 
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tblDistributorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDistributorMouseClicked
    int selectedRow = tblDistributor.getSelectedRow();
    if (selectedRow != -1) {
        txtNama.setText(tblDistributor.getValueAt(selectedRow, 1).toString());
        txtUsername.setText(tblDistributor.getValueAt(selectedRow, 2).toString());
        txtPassword.setText(tblDistributor.getValueAt(selectedRow, 3).toString());
        txtJumlah.setText(tblDistributor.getValueAt(selectedRow, 4).toString());
        txtNamaUsaha.setText(tblDistributor.getValueAt(selectedRow, 5).toString());
        txtWilayahPasar.setText(tblDistributor.getValueAt(selectedRow, 6).toString());
    }
    }//GEN-LAST:event_tblDistributorMouseClicked

    private void btnPerbaruiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerbaruiActionPerformed
        loadTabelDistributor();
        JOptionPane.showMessageDialog(this, "Tabel diperbarui dengan data terbaru!");        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerbaruiActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        new MenuKelolaDistributor().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KelolaAkunDistributor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnPerbarui;
    private javax.swing.JButton btnTambah;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JLabel lblKelolaAkunDistributorBg;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNamaUsaha;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblWilayahPasar;
    private javax.swing.JTable tblDistributor;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNamaUsaha;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtWilayahPasar;
    // End of variables declaration//GEN-END:variables
}
