/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author Asus TUF
 */
public class KelolaAkunPetani extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KelolaAkunPetani.class.getName());
    private final Controller.petaniController petaniCtrl = new Controller.petaniController();
    private String selectedId = null;

    /**
     * Creates new form KelolaAkun
     */
    public KelolaAkunPetani() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null); 
        this.setResizable(false);
        loadData();
      
    java.net.URL imgURL = getClass().getResource("/KelolaAkunBg.png");
    if (imgURL != null) {
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
        java.awt.Image img = icon.getImage().getScaledInstance(
            800, 
            500, 
            java.awt.Image.SCALE_SMOOTH
        );
        lblKelolaAkunBg.setIcon(new javax.swing.ImageIcon(img));
    } else {
        System.err.println("Gambar tidak ditemukan di /resources/KelolaAkunBg.png");
    }
    
    tblPetani.getSelectionModel().addListSelectionListener(e -> {
        int row = tblPetani.getSelectedRow();
        if (row != -1) {
            selectedId = tblPetani.getValueAt(row, 0).toString();
            txtNama.setText(tblPetani.getValueAt(row, 1).toString());
            txtUsername.setText(tblPetani.getValueAt(row, 2).toString());
            txtPassword.setText(tblPetani.getValueAt(row, 3).toString());
            txtNoTelp.setText(tblPetani.getValueAt(row, 4).toString());
            txtNamaSawah.setText(tblPetani.getValueAt(row, 5).toString());
            txtLokasi.setText(tblPetani.getValueAt(row, 6).toString());
            txtLuasSawah.setText(tblPetani.getValueAt(row, 7).toString());
        }
    });
    }
    
    private void loadData() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.addColumn("ID Petani");
        model.addColumn("Nama Lengkap");
        model.addColumn("Username");
        model.addColumn("Password");
        model.addColumn("No. Telp");
        model.addColumn("Nama Sawah");
        model.addColumn("Lokasi");
        model.addColumn("Luas Lahan");

        for (Model.Petani p : petaniCtrl.getAllPetaniWithSawah()) {
            model.addRow(new Object[]{
                p.getIdPetani(),
                p.getNamaLengkap(),
                p.getUsername(),
                p.getPassword(),
                p.getNoTelp(),
                p.getNamaSawah() != null ? p.getNamaSawah() : "",
                p.getLokasi() != null ? p.getLokasi() : "",
                p.getLuasLahan()
            });
        }

        tblPetani.setModel(model);
    }
    private void clearFields() {    
            txtNama.setText("");
            txtUsername.setText("");
            txtPassword.setText("");
            txtNoTelp.setText("");
            txtNamaSawah.setText("");
            txtLokasi.setText("");
            txtLuasSawah.setText("");
            selectedId = null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPassword = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblNoTelp = new javax.swing.JLabel();
        lblNamaSawah = new javax.swing.JLabel();
        lblLuasSawah = new javax.swing.JLabel();
        lblLokasiSawah = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtNoTelp = new javax.swing.JTextField();
        txtNamaSawah = new javax.swing.JTextField();
        txtLokasi = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtLuasSawah = new javax.swing.JTextField();
        btnHapus = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPetani = new javax.swing.JTable();
        btnPerbarui = new javax.swing.JButton();
        btnTambah1 = new javax.swing.JButton();
        lblKelolaAkunBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 538));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");
        jPanel1.add(lblPassword);
        lblPassword.setBounds(110, 170, 190, 20);

        lblNama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNama.setForeground(new java.awt.Color(255, 255, 255));
        lblNama.setText("Nama Petani");
        jPanel1.add(lblNama);
        lblNama.setBounds(110, 70, 170, 20);

        lblNoTelp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNoTelp.setForeground(new java.awt.Color(255, 255, 255));
        lblNoTelp.setText("Nomor Telepon");
        jPanel1.add(lblNoTelp);
        lblNoTelp.setBounds(110, 220, 190, 20);

        lblNamaSawah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNamaSawah.setForeground(new java.awt.Color(255, 255, 255));
        lblNamaSawah.setText("Nama Sawah");
        jPanel1.add(lblNamaSawah);
        lblNamaSawah.setBounds(420, 70, 190, 20);

        lblLuasSawah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLuasSawah.setForeground(new java.awt.Color(255, 255, 255));
        lblLuasSawah.setText("Luas Sawah (m2)");
        jPanel1.add(lblLuasSawah);
        lblLuasSawah.setBounds(420, 120, 190, 20);

        lblLokasiSawah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLokasiSawah.setForeground(new java.awt.Color(255, 255, 255));
        lblLokasiSawah.setText("Lokasi Sawah");
        jPanel1.add(lblLokasiSawah);
        lblLokasiSawah.setBounds(420, 170, 190, 20);

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username");
        jPanel1.add(lblUsername);
        lblUsername.setBounds(110, 120, 190, 20);

        txtNoTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoTelpActionPerformed(evt);
            }
        });
        jPanel1.add(txtNoTelp);
        txtNoTelp.setBounds(110, 240, 260, 30);

        txtNamaSawah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaSawahActionPerformed(evt);
            }
        });
        jPanel1.add(txtNamaSawah);
        txtNamaSawah.setBounds(420, 90, 260, 30);

        txtLokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLokasiActionPerformed(evt);
            }
        });
        jPanel1.add(txtLokasi);
        txtLokasi.setBounds(420, 190, 260, 30);

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(txtPassword);
        txtPassword.setBounds(110, 190, 260, 30);

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNama);
        txtNama.setBounds(110, 90, 260, 30);

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsername);
        txtUsername.setBounds(110, 140, 260, 30);

        txtLuasSawah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLuasSawahActionPerformed(evt);
            }
        });
        jPanel1.add(txtLuasSawah);
        txtLuasSawah.setBounds(420, 140, 260, 30);

        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(0, 102, 0));
        btnHapus.setText("Hapus");
        btnHapus.setToolTipText("");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus);
        btnHapus.setBounds(610, 240, 90, 30);

        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(0, 102, 0));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali);
        btnKembali.setBounds(660, 30, 90, 30);

        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(0, 102, 0));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit);
        btnEdit.setBounds(520, 240, 80, 30);

        tblPetani.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id_petani", "nama_lengkap", "username", "password", "no_telp", "nama_sawah", "lokasi", "luas_lahan", "role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPetani);
        if (tblPetani.getColumnModel().getColumnCount() > 0) {
            tblPetani.getColumnModel().getColumn(0).setResizable(false);
            tblPetani.getColumnModel().getColumn(1).setResizable(false);
            tblPetani.getColumnModel().getColumn(2).setResizable(false);
            tblPetani.getColumnModel().getColumn(3).setResizable(false);
            tblPetani.getColumnModel().getColumn(4).setResizable(false);
            tblPetani.getColumnModel().getColumn(5).setResizable(false);
            tblPetani.getColumnModel().getColumn(6).setResizable(false);
            tblPetani.getColumnModel().getColumn(7).setResizable(false);
            tblPetani.getColumnModel().getColumn(8).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(80, 310, 640, 140);

        btnPerbarui.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPerbarui.setForeground(new java.awt.Color(0, 102, 0));
        btnPerbarui.setText("Perbarui ");
        btnPerbarui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerbaruiActionPerformed(evt);
            }
        });
        jPanel1.add(btnPerbarui);
        btnPerbarui.setBounds(80, 450, 130, 30);

        btnTambah1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTambah1.setForeground(new java.awt.Color(0, 102, 0));
        btnTambah1.setText("Tambah");
        btnTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambah1);
        btnTambah1.setBounds(420, 240, 90, 30);

        lblKelolaAkunBg.setText("jLabel8");
        lblKelolaAkunBg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKelolaAkunBgMouseClicked(evt);
            }
        });
        jPanel1.add(lblKelolaAkunBg);
        lblKelolaAkunBg.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoTelpActionPerformed

    private void txtNamaSawahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaSawahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaSawahActionPerformed

    private void txtLokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLokasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLokasiActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtLuasSawahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLuasSawahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLuasSawahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
    if (selectedId == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu!");
        return;
    }

    int confirm = javax.swing.JOptionPane.showConfirmDialog(
        this, "Apakah yakin ingin menghapus data ini?", "Konfirmasi", javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        if (petaniCtrl.delete(selectedId)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            loadData();
            clearFields();
        } else {
    JOptionPane.showMessageDialog(this, 
        "Tidak dapat menghapus data petani karena masih memiliki data hasil panen.",
        "Gagal Hapus", JOptionPane.WARNING_MESSAGE);
}
    }       
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        new MenuKelolaPetani().setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
    Model.Petani p = new Model.Petani();
    p.setIdPetani(selectedId);
    p.setNamaLengkap(txtNama.getText());
    p.setUsername(txtUsername.getText());
    p.setPassword(txtPassword.getText());
    p.setNoTelp(txtNoTelp.getText());
    p.setNamaSawah(txtNamaSawah.getText());
    p.setLokasi(txtLokasi.getText());
    p.setLuasLahan(Integer.parseInt(txtLuasSawah.getText()));

    if (petaniCtrl.editPetani(p)) {
        JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
        loadData();
        tblPetani.revalidate();
        tblPetani.repaint();
        clearFields();
    } else {
        JOptionPane.showMessageDialog(this, "Gagal memperbarui data!");
    }    
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnPerbaruiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerbaruiActionPerformed
    try {
        loadData(); 
        clearFields();
        JOptionPane.showMessageDialog(this, "Tabel berhasil diperbarui!", "Info", JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memperbarui tabel: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }       
    }//GEN-LAST:event_btnPerbaruiActionPerformed

    private void btnTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah1ActionPerformed
    Model.Petani p = new Model.Petani();
    p.setNamaLengkap(txtNama.getText());
    p.setUsername(txtUsername.getText());
    p.setPassword(txtPassword.getText());
    p.setNoTelp(txtNoTelp.getText());
    p.setNamaSawah(txtNamaSawah.getText());
    p.setLokasi(txtLokasi.getText());

    String luasStr = txtLuasSawah.getText().trim();
    int luasLahan;
    try {
        luasLahan = Integer.parseInt(luasStr);
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Luas sawah harus berupa angka!",
            "Input Tidak Valid",
            javax.swing.JOptionPane.ERROR_MESSAGE
        );
        return; 
    }

    p.setLuasLahan(luasLahan);

    if (p.getNamaLengkap().isEmpty() || p.getUsername().isEmpty() || 
        p.getPassword().isEmpty() || p.getNoTelp().isEmpty() || 
        p.getNamaSawah().isEmpty() || p.getLokasi().isEmpty()) {

        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Semua field wajib diisi!",
            "Input Tidak Lengkap",
            javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    if (petaniCtrl.tambahPetani(p)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
        loadData();
        clearFields();
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal menambah data!");
    }
    }//GEN-LAST:event_btnTambah1ActionPerformed

    private void lblKelolaAkunBgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKelolaAkunBgMouseClicked
    int row = tblPetani.getSelectedRow();
    if (row != -1) {
        selectedId = tblPetani.getValueAt(row, 0).toString();
        txtNama.setText(tblPetani.getValueAt(row, 1).toString());
        txtUsername.setText(tblPetani.getValueAt(row, 2).toString());
        txtPassword.setText(tblPetani.getValueAt(row, 3).toString());
        txtNoTelp.setText(tblPetani.getValueAt(row, 4).toString());
        txtNamaSawah.setText(tblPetani.getValueAt(row, 5).toString());
        txtLokasi.setText(tblPetani.getValueAt(row, 6).toString());
        txtLuasSawah.setText(tblPetani.getValueAt(row, 7).toString());
    }        
    }//GEN-LAST:event_lblKelolaAkunBgMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KelolaAkunPetani().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnPerbarui;
    private javax.swing.JButton btnTambah1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKelolaAkunBg;
    private javax.swing.JLabel lblLokasiSawah;
    private javax.swing.JLabel lblLuasSawah;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNamaSawah;
    private javax.swing.JLabel lblNoTelp;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTable tblPetani;
    private javax.swing.JTextField txtLokasi;
    private javax.swing.JTextField txtLuasSawah;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNamaSawah;
    private javax.swing.JTextField txtNoTelp;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
