/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.permintaanController;
import Model.Permintaan;
import Session.UserSession;
import java.util.List;
import javax.swing.JOptionPane;
import com.github.lgooddatepicker.components.DatePicker;
import java.time.LocalDate;
/**
 *
 * @author Asus TUF
 */
public class KelolaPermintaan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KelolaPermintaan.class.getName());
    private final permintaanController controller = new permintaanController();
    private String selectedPermintaanId = null;
    /**
     * Creates new form KelolaAkunDistributor
     */
    public KelolaPermintaan() {
        initComponents();
        this.pack(); 
        this.setLocationRelativeTo(null); 
        this.setResizable(false);
        loadTabelPermintaan();

    java.net.URL imgURL = getClass().getResource("/KelolaPermintaanBg.png");
    if (imgURL != null) {
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
        java.awt.Image img = icon.getImage().getScaledInstance(
            800, 
            500, 
            java.awt.Image.SCALE_SMOOTH
        );
        lblKelolaPermintaanBg.setIcon(new javax.swing.ImageIcon(img));
    } else {
        System.err.println("Gambar tidak ditemukan di /resources/KelolaPermintaanBg.png");
    }
    }

    private void loadTabelPermintaan() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.addColumn("ID Permintaan");
        model.addColumn("Jumlah Permintaan");
        model.addColumn("ID Panen");
        model.addColumn("ID Distributor");
        model.addColumn("ID Admin");
        model.addColumn("Status");
        model.addColumn("Tanggal Permintaan");

        List<Permintaan> list = controller.getAllPermintaan();
        for (Permintaan p : list) {
            model.addRow(new Object[]{
                p.getIdPermintaan(),
                p.getJumlahPermintaan(),
                p.getIdPanen(),
                p.getIdDistributor(),
                p.getIdAdmin(),
                p.getStatus(),
                p.getTanggalPermintaan()
            });
        }
        tblPermintaan.setModel(model);
    }

    private void clearForm() {
        txtNama.setText("");
        txtJumlah.setText("");
        cmbStatus.setSelectedIndex(0);
        DateTglPanen.setDate(null);
        selectedPermintaanId = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTanggal = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        lblNoTelp = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        lblNama = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPermintaan = new javax.swing.JTable();
        btnKembali = new javax.swing.JButton();
        btnPerbarui = new javax.swing.JButton();
        DateTglPanen = new com.github.lgooddatepicker.components.DatePicker();
        lblKelolaPermintaanBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        lblTanggal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTanggal.setForeground(new java.awt.Color(255, 255, 255));
        lblTanggal.setText("Tanggal");
        jPanel1.add(lblTanggal);
        lblTanggal.setBounds(420, 170, 200, 20);

        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblStatus.setText("Status");
        jPanel1.add(lblStatus);
        lblStatus.setBounds(420, 90, 200, 20);
        jPanel1.add(txtNama);
        txtNama.setBounds(110, 120, 260, 30);

        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });
        jPanel1.add(txtJumlah);
        txtJumlah.setBounds(110, 200, 260, 30);

        lblNoTelp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNoTelp.setForeground(new java.awt.Color(255, 255, 255));
        lblNoTelp.setText("Jumlah Permintaan (Kg)");
        jPanel1.add(lblNoTelp);
        lblNoTelp.setBounds(110, 170, 200, 20);

        cmbStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbStatus.setForeground(new java.awt.Color(0, 102, 0));
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "menunggu", "ditolak", "diterima", "dipenuhi" }));
        cmbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusActionPerformed(evt);
            }
        });
        jPanel1.add(cmbStatus);
        cmbStatus.setBounds(420, 120, 260, 30);

        lblNama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNama.setForeground(new java.awt.Color(255, 255, 255));
        lblNama.setText("Nama Distributor");
        jPanel1.add(lblNama);
        lblNama.setBounds(110, 90, 200, 20);

        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(0, 102, 0));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus);
        btnHapus.setBounds(450, 250, 100, 31);

        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(0, 102, 0));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambah);
        btnTambah.setBounds(210, 250, 100, 31);

        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(0, 102, 0));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit);
        btnEdit.setBounds(330, 250, 100, 31);

        tblPermintaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id_permintaan", "jumlah_permintaan", "id_panen", "id_distributor", "id_admin", "status", "tanggal_permintaan"
            }
        ));
        tblPermintaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPermintaanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPermintaan);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 310, 660, 110);

        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(0, 102, 0));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali);
        btnKembali.setBounds(660, 30, 90, 31);

        btnPerbarui.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPerbarui.setForeground(new java.awt.Color(0, 102, 0));
        btnPerbarui.setText("Perbarui");
        jPanel1.add(btnPerbarui);
        btnPerbarui.setBounds(70, 420, 90, 31);
        jPanel1.add(DateTglPanen);
        DateTglPanen.setBounds(420, 200, 260, 30);

        lblKelolaPermintaanBg.setText("jLabel2");
        jPanel1.add(lblKelolaPermintaanBg);
        lblKelolaPermintaanBg.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int row = tblPermintaan.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus!");
            return;
        }

        String id = tblPermintaan.getValueAt(row, 0).toString();
        if (controller.deletePermintaan(id)) {
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            loadTabelPermintaan();
            clearForm();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menghapus data!");
        }     // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
    try {
        int jumlah = Integer.parseInt(txtJumlah.getText());
        String status = cmbStatus.getSelectedItem().toString();

        Database.hasilPanenService panenSrv = new Database.hasilPanenService();
        String idPanen = panenSrv.getLastPanenId();
        if (idPanen == null) {
            JOptionPane.showMessageDialog(this, "Belum ada data hasil panen di database!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String idAdmin = UserSession.getIdUser();
        if (idAdmin == null || idAdmin.isBlank()) {
            JOptionPane.showMessageDialog(this, "Session admin tidak valid! Silakan login ulang.");
            return;
        }
      
        System.out.println("[DEBUG] ID Admin aktif: " + idAdmin);
        LocalDate selectedDate = DateTglPanen.getDate();
        if (selectedDate == null) {
            JOptionPane.showMessageDialog(this, "Tanggal belum dipilih!");
            return;
        }
        
        Model.Permintaan p = new Model.Permintaan();
        p.setIdPermintaan(null);
        p.setJumlahPermintaan(jumlah);
        p.setIdPanen(idPanen);
        p.setIdDistributor("DIS01"); 
        p.setIdAdmin(idAdmin);
        p.setTanggalPermintaan(java.sql.Date.valueOf(selectedDate));
        p.setStatus(status);

        if (controller.tambahPermintaan(p)) {
            JOptionPane.showMessageDialog(this, "Permintaan berhasil ditambahkan!");
            loadTabelPermintaan();
            clearForm();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menambah permintaan!", "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Jumlah harus berupa angka!", "Peringatan", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
      int row = tblPermintaan.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin diubah!");
            return;
        }

        Permintaan p = new Permintaan();
        p.setIdPermintaan(tblPermintaan.getValueAt(row, 0).toString());
        p.setJumlahPermintaan(Integer.parseInt(txtJumlah.getText()));
        p.setIdPanen(tblPermintaan.getValueAt(row, 2).toString());
        p.setIdDistributor(tblPermintaan.getValueAt(row, 3).toString());
        String idAdmin = UserSession.getIdUser();
        if (idAdmin == null || idAdmin.isBlank()) {
            JOptionPane.showMessageDialog(this, "Session admin tidak valid! Silakan login ulang.");
            return;
        }
        p.setIdAdmin(idAdmin);
        p.setStatus(cmbStatus.getSelectedItem().toString());

    LocalDate selectedDate = DateTglPanen.getDate();
    if (selectedDate == null) {
        JOptionPane.showMessageDialog(this, "Tanggal belum dipilih!");
        return;
    }
    p.setTanggalPermintaan(java.sql.Date.valueOf(selectedDate));

        if (controller.updatePermintaan(p)) {
            JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
            loadTabelPermintaan();
            clearForm();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui data!");
        }      // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        new MenuKelolaDistributor().setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void tblPermintaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPermintaanMouseClicked
        int row = tblPermintaan.getSelectedRow();
        if (row != -1) {
            selectedPermintaanId = tblPermintaan.getValueAt(row, 0).toString();
            txtNama.setText(tblPermintaan.getValueAt(row, 3).toString());
            txtJumlah.setText(tblPermintaan.getValueAt(row, 1).toString());
            cmbStatus.setSelectedItem(tblPermintaan.getValueAt(row, 5).toString());

            try {
                Object val = tblPermintaan.getValueAt(row, 6);
                if (val != null && !val.toString().isBlank()) {
                    LocalDate parsed = java.sql.Date.valueOf(val.toString()).toLocalDate();
                    DateTglPanen.setDate(parsed);
                } else {
                    DateTglPanen.setDate(LocalDate.now());
                }
            } catch (Exception e) {
                System.err.println("Gagal parse tanggal: " + e.getMessage());
                DateTglPanen.setDate(LocalDate.now());
            }
        }    // TODO add your handling code here:
    }//GEN-LAST:event_tblPermintaanMouseClicked

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KelolaPermintaan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DatePicker DateTglPanen;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnPerbarui;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKelolaPermintaanBg;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNoTelp;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JTable tblPermintaan;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
