/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Session.UserSession;
import com.github.lgooddatepicker.components.DatePicker;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus TUF
 */
public class KelolaPanen extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KelolaPanen.class.getName());
    private final Controller.hasilPanenController panenCtrl = new Controller.hasilPanenController();
    private String selectedPanenId = null;
    private String selectedPetaniId = null;

    public KelolaPanen() {
        initComponents();
        this.pack(); 
        this.setLocationRelativeTo(null); 
        this.setResizable(false);
        loadData();
        
    java.net.URL imgURL = getClass().getResource("/KelolaPanenBg.png");
    if (imgURL != null) {
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
        java.awt.Image img = icon.getImage().getScaledInstance(
            800, 
            500,
            java.awt.Image.SCALE_SMOOTH
        );
        lblKelolaPanenBg.setIcon(new javax.swing.ImageIcon(img));
    } else {
        System.err.println("Gambar tidak ditemukan di /resources/KelolaPanenBg.png");
    }
    }
    

private void loadData() {
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
    model.addColumn("ID Panen");
    model.addColumn("Jumlah Panen (Kg)");
    model.addColumn("Stok Gudang");
    model.addColumn("Satuan");
    model.addColumn("Tanggal Panen");
    model.addColumn("ID Petani");
    model.addColumn("ID Admin");

    for (Model.hasilPanen h : panenCtrl.getAllPanen()) {
        model.addRow(new Object[]{
            h.getIdPanen(),
            h.getJumlahPanen(),
            h.getStokGudang(),
            h.getSatuan(),
            h.getTanggalPanen(),
            h.getIdPetani(),
            h.getIdAdmin()
        });
    }
    tblHasilPanen.setModel(model);
    tblHasilPanen.revalidate();
    tblHasilPanen.repaint();

}

 
private void clearFields() {
    txtJumlahPanen.setText("");
    DateTglPanen.setDate(LocalDate.now());
    cmbSatuan.setSelectedIndex(0);
    selectedPanenId = null;
    txtJumlahPanen.setEnabled(false);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTanggalPanen = new javax.swing.JLabel();
        lblSatuan = new javax.swing.JLabel();
        cmbSatuan = new javax.swing.JComboBox<>();
        lblJumlahPanen = new javax.swing.JLabel();
        txtJumlahPanen = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHasilPanen = new javax.swing.JTable();
        btnPerbarui = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        DateTglPanen = new com.github.lgooddatepicker.components.DatePicker();
        lblKelolaPanenBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        lblTanggalPanen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTanggalPanen.setForeground(new java.awt.Color(255, 255, 255));
        lblTanggalPanen.setText("Tanggal Panen");
        jPanel1.add(lblTanggalPanen);
        lblTanggalPanen.setBounds(90, 170, 180, 20);

        lblSatuan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSatuan.setForeground(new java.awt.Color(255, 255, 255));
        lblSatuan.setText("Satuan");
        jPanel1.add(lblSatuan);
        lblSatuan.setBounds(420, 110, 180, 20);

        cmbSatuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kg", "Ton" }));
        cmbSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSatuanActionPerformed(evt);
            }
        });
        jPanel1.add(cmbSatuan);
        cmbSatuan.setBounds(420, 130, 110, 30);

        lblJumlahPanen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJumlahPanen.setForeground(new java.awt.Color(255, 255, 255));
        lblJumlahPanen.setText("Jumlan Panen");
        jPanel1.add(lblJumlahPanen);
        lblJumlahPanen.setBounds(90, 110, 180, 20);

        txtJumlahPanen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahPanenActionPerformed(evt);
            }
        });
        jPanel1.add(txtJumlahPanen);
        txtJumlahPanen.setBounds(90, 130, 260, 30);

        tblHasilPanen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id_panen", "jumlah_panen", "stok_gudang", "satuan", "tanggal_panen", "id_petani", "id_admin"
            }
        ));
        tblHasilPanen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHasilPanenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHasilPanen);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 280, 660, 130);

        btnPerbarui.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPerbarui.setForeground(new java.awt.Color(0, 102, 0));
        btnPerbarui.setText("Perbarui");
        jPanel1.add(btnPerbarui);
        btnPerbarui.setBounds(70, 410, 90, 30);

        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(0, 102, 0));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambah);
        btnTambah.setBounds(420, 190, 90, 30);

        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(0, 102, 0));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali);
        btnKembali.setBounds(640, 40, 90, 30);

        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(0, 102, 0));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus);
        btnHapus.setBounds(620, 190, 90, 30);

        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(0, 102, 0));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit);
        btnEdit.setBounds(520, 190, 90, 30);
        jPanel1.add(DateTglPanen);
        DateTglPanen.setBounds(90, 200, 260, 30);

        lblKelolaPanenBg.setText("jLabel4");
        jPanel1.add(lblKelolaPanenBg);
        lblKelolaPanenBg.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSatuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSatuanActionPerformed

    private void tblHasilPanenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHasilPanenMouseClicked
    int row = tblHasilPanen.getSelectedRow();
    if (row != -1) {
        selectedPanenId = tblHasilPanen.getValueAt(row, 0).toString();
        txtJumlahPanen.setText(tblHasilPanen.getValueAt(row, 1).toString());
        cmbSatuan.setSelectedItem(tblHasilPanen.getValueAt(row, 3).toString());
        selectedPetaniId = tblHasilPanen.getValueAt(row, 5).toString();

        try {
            Object val = tblHasilPanen.getValueAt(row, 4);
            if (val != null) {
                LocalDate parsed = java.sql.Date.valueOf(val.toString()).toLocalDate();
                DateTglPanen.setDate(parsed);
            } else {
                DateTglPanen.setDate(LocalDate.now());
            }
        } catch (Exception e) {
            System.err.println("Gagal parse tanggal: " + e.getMessage());
            DateTglPanen.setDate(LocalDate.now());
        }

        txtJumlahPanen.setEnabled(true);
    }
    }//GEN-LAST:event_tblHasilPanenMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
    if (selectedPetaniId == null || selectedPetaniId.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Silakan pilih data petani terlebih dahulu sebelum menambah panen!",
            "Peringatan",
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        if (!txtJumlahPanen.isEnabled()) {
            JOptionPane.showMessageDialog(this,
                "Anda belum memilih data panen yang valid!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        double jumlah = Double.parseDouble(txtJumlahPanen.getText());
        String satuan = cmbSatuan.getSelectedItem().toString();
        LocalDate selectedDate = DateTglPanen.getDate();

        if (selectedDate == null) {
            JOptionPane.showMessageDialog(this, "Tanggal panen belum dipilih!");
            return;
        }

        boolean success = panenCtrl.tambahPanen(selectedPetaniId, jumlah, satuan);
        if (success) {
            JOptionPane.showMessageDialog(this, "Data panen berhasil ditambahkan!");
            loadData();
            clearFields();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menambah data panen!");
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Jumlah harus berupa angka!");
    }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
    if (selectedPanenId == null) {
        JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu!");
        return;
    }

    try {
        double jumlah = Double.parseDouble(txtJumlahPanen.getText());
        String satuan = cmbSatuan.getSelectedItem().toString();
        LocalDate selectedDate = DateTglPanen.getDate(); 

        if (selectedDate == null) {
            JOptionPane.showMessageDialog(this, "Tanggal panen belum dipilih!");
            return;
        }

        String idAdmin = Session.UserSession.getIdUser();
        if (idAdmin == null || idAdmin.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sesi admin tidak ditemukan! Silakan login ulang.");
            return;
        }

        boolean success = panenCtrl.editPanen(selectedPanenId, (int) jumlah, satuan, selectedDate, idAdmin);

        if (success) {
            JOptionPane.showMessageDialog(this, "Data panen berhasil diperbarui!");
            loadData();
            clearFields();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui data!");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Jumlah harus berupa angka!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
      if (selectedPanenId == null) {
            JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this, "Yakin ingin menghapus data panen ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            boolean success = panenCtrl.delete(selectedPanenId);
            if (success) {
                JOptionPane.showMessageDialog(this, "Data panen berhasil dihapus!");
                loadData();
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data panen!");
            }
        }       
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtJumlahPanenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahPanenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahPanenActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        MenuKelolaPetani kelolaakun = new MenuKelolaPetani();
        kelolaakun.setVisible(true);
        this.dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KelolaPanen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DatePicker DateTglPanen;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnPerbarui;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cmbSatuan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJumlahPanen;
    private javax.swing.JLabel lblKelolaPanenBg;
    private javax.swing.JLabel lblSatuan;
    private javax.swing.JLabel lblTanggalPanen;
    private javax.swing.JTable tblHasilPanen;
    private javax.swing.JTextField txtJumlahPanen;
    // End of variables declaration//GEN-END:variables
}
