/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus TUF
 */
public class MenuDistributor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuDistributor.class.getName());

    /**
     * Creates new form PetaniDashboard
     */
    public MenuDistributor() {
        initComponents();
        this.pack(); 
        this.setLocationRelativeTo(null); 
        this.setResizable(false);  
        java.net.URL petaniURL = getClass().getResource("/TombolInfoPetani.png");
    if (petaniURL != null) {
        javax.swing.ImageIcon petaniIcon = new javax.swing.ImageIcon(petaniURL);
        java.awt.Image imgPetani = petaniIcon.getImage().getScaledInstance(300, 300, java.awt.Image.SCALE_SMOOTH);

        btnInfoPetani.setIcon(new javax.swing.ImageIcon(imgPetani));
        btnInfoPetani.setText("Info Petani");

        btnInfoPetani.setBorderPainted(false);
        btnInfoPetani.setContentAreaFilled(false);
        btnInfoPetani.setFocusPainted(false);
        btnInfoPetani.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInfoPetani.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInfoPetani.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInfoPetani.setPreferredSize(new java.awt.Dimension(220, 240));
    } else {
        System.err.println("Gambar tidak ditemukan di /resources/TombolInfoPetani.png");
    }
    java.net.URL permintaanURL = getClass().getResource("/TombolPermintaanDistributor.png");
    if (permintaanURL != null) {
        javax.swing.ImageIcon permintaanIcon = new javax.swing.ImageIcon(permintaanURL);
        java.awt.Image imgPermintaan = permintaanIcon.getImage().getScaledInstance(300, 300, java.awt.Image.SCALE_SMOOTH);

        btnPermintaan.setIcon(new javax.swing.ImageIcon(imgPermintaan));
        btnPermintaan.setText("Info Petani");

        btnPermintaan.setBorderPainted(false);
        btnPermintaan.setContentAreaFilled(false);
        btnPermintaan.setFocusPainted(false);
        btnPermintaan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPermintaan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPermintaan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPermintaan.setPreferredSize(new java.awt.Dimension(220, 240));
    } else {
        System.err.println("Gambar tidak ditemukan di /resources/TombolPermintaanDistributor.png");
    }

    java.net.URL imgURL = getClass().getResource("/MenuDistributorBg.png");
    if (imgURL != null) {
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
        java.awt.Image img = icon.getImage().getScaledInstance(
            800, 
            500, 
            java.awt.Image.SCALE_SMOOTH
        );
        lblDistributorBg.setIcon(new javax.swing.ImageIcon(img));
    } else {
        System.err.println("Gambar tidak ditemukan di /resources/MenuPetaniBg.png");
    }
}
    
    public MenuDistributor(String username) {
        this(); 
        setTitle("Menu Distributor - " + username); 
        JLabel lblWelcome = new JLabel("Selamat datang, " + username + "!");
        lblWelcome.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
        lblWelcome.setForeground(Color.WHITE);
        lblWelcome.setBounds(30, 20, 400, 30);
        jPanel1.add(lblWelcome);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnInfoPetani = new javax.swing.JButton();
        btnPermintaan = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        lblDistributorBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        btnInfoPetani.setText("Info Petani");
        btnInfoPetani.setPreferredSize(new java.awt.Dimension(92, 23));
        btnInfoPetani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoPetaniActionPerformed(evt);
            }
        });
        jPanel1.add(btnInfoPetani);
        btnInfoPetani.setBounds(160, 160, 250, 260);

        btnPermintaan.setText("Permintaan");
        btnPermintaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPermintaanActionPerformed(evt);
            }
        });
        jPanel1.add(btnPermintaan);
        btnPermintaan.setBounds(390, 160, 250, 260);

        btnKeluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(0, 102, 0));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnKeluar);
        btnKeluar.setBounds(660, 40, 90, 30);

        lblDistributorBg.setText("lblDistributorBg");
        lblDistributorBg.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.add(lblDistributorBg);
        lblDistributorBg.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInfoPetaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoPetaniActionPerformed
        InfoPetaniDistributorForm infopetani = new InfoPetaniDistributorForm();
        infopetani.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_btnInfoPetaniActionPerformed

    private void btnPermintaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPermintaanActionPerformed
        PermintaanDistributorForm permintaan = new PermintaanDistributorForm();
        permintaan.setVisible(true);
        this.dispose();       
    }//GEN-LAST:event_btnPermintaanActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
       int confirm = JOptionPane.showConfirmDialog(
        this,
        "Apakah Anda yakin ingin keluar?",
        "Konfirmasi Keluar",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE
    );
    if (confirm == JOptionPane.YES_OPTION) {
        new DashboardLogin().setVisible(true);
        this.dispose();
    }       
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuDistributor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInfoPetani;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnPermintaan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDistributorBg;
    // End of variables declaration//GEN-END:variables
}
