/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Asus TUF
 */
public class MenuKelolaPetani extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuKelolaPetani.class.getName());

    /**
     * Creates new form MenuKelolaPetani
     */
    public MenuKelolaPetani() {
        initComponents();
        this.pack(); 
        this.setLocationRelativeTo(null); 
        this.setResizable(false);
    java.net.URL imgURL = getClass().getResource("/KelolaPetaniBg.png");
    if (imgURL != null) {
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
        java.awt.Image img = icon.getImage().getScaledInstance(
            800,
            500, 
            java.awt.Image.SCALE_SMOOTH
        );
        lblKelolaPetaniBg.setIcon(new javax.swing.ImageIcon(img));
    } else {
        System.err.println("ambar tidak ditemukan di /resources/KelolaPetaniBg.png");
    }
    java.net.URL keloladistributorURL = getClass().getResource("/TombolKelolaAkun.png");
    if (keloladistributorURL != null) {
        javax.swing.ImageIcon keloladistributorIcon = new javax.swing.ImageIcon(keloladistributorURL);
        java.awt.Image imgKelolaDistributor = keloladistributorIcon.getImage().getScaledInstance(300, 300, java.awt.Image.SCALE_SMOOTH);

        btnKelolaAkun.setIcon(new javax.swing.ImageIcon(imgKelolaDistributor));
        btnKelolaAkun.setText("Info Petani");

        btnKelolaAkun.setBorderPainted(false);
        btnKelolaAkun.setContentAreaFilled(false);
        btnKelolaAkun.setFocusPainted(false);
        btnKelolaAkun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKelolaAkun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKelolaAkun.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKelolaAkun.setPreferredSize(new java.awt.Dimension(220, 240));
    } else {
        System.err.println("Gambar tidak ditemukan di /resources/TombolKelolaAkun.png");
    }

    java.net.URL kelolapanenURL = getClass().getResource("/TombolKelolaPanen.png");
    if (kelolapanenURL != null) {
        javax.swing.ImageIcon kelolapanenIcon = new javax.swing.ImageIcon(kelolapanenURL);
        java.awt.Image imgKelolaPanen = kelolapanenIcon.getImage().getScaledInstance(300, 300, java.awt.Image.SCALE_SMOOTH);

        btnKelolaPanen.setIcon(new javax.swing.ImageIcon(imgKelolaPanen));
        btnKelolaPanen.setText("Info Petani");

        btnKelolaPanen.setBorderPainted(false);
        btnKelolaPanen.setContentAreaFilled(false);
        btnKelolaPanen.setFocusPainted(false);
        btnKelolaPanen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKelolaPanen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKelolaPanen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKelolaPanen.setPreferredSize(new java.awt.Dimension(220, 240));
    } else {
        System.err.println("Gambar tidak ditemukan di /resources/TombolKelolaPanen.png");
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnKelolaAkun = new javax.swing.JButton();
        btnKelolaPanen = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        lblKelolaPetaniBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 538));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        btnKelolaAkun.setText("Kelola Akun");
        btnKelolaAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaAkunActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaAkun);
        btnKelolaAkun.setBounds(160, 160, 220, 220);

        btnKelolaPanen.setText("Kelola Panen");
        btnKelolaPanen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaPanenActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaPanen);
        btnKelolaPanen.setBounds(400, 160, 220, 220);

        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(0, 102, 0));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali);
        btnKembali.setBounds(660, 40, 90, 30);

        lblKelolaPetaniBg.setText("jLabel1");
        jPanel1.add(lblKelolaPetaniBg);
        lblKelolaPetaniBg.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKelolaAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaAkunActionPerformed
        KelolaAkunPetani kelolaakun = new KelolaAkunPetani();
        kelolaakun.setVisible(true);
        this.dispose();         
    }//GEN-LAST:event_btnKelolaAkunActionPerformed

    private void btnKelolaPanenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaPanenActionPerformed
        KelolaPanen kelolapanen = new KelolaPanen();
        kelolapanen.setVisible(true);
    
        // Tutup halaman dashboard sekarang
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnKelolaPanenActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        MenuAdmin petani = new MenuAdmin();
        petani.setVisible(true);
        this.dispose();             
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuKelolaPetani().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKelolaAkun;
    private javax.swing.JButton btnKelolaPanen;
    private javax.swing.JButton btnKembali;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblKelolaPetaniBg;
    // End of variables declaration//GEN-END:variables
}
