/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Asus TUF
 */
public class MenuKelolaDistributor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuKelolaDistributor.class.getName());

    /**
     * Creates new form MenuKelolaDistributor
     */
    public MenuKelolaDistributor() {
        initComponents();
        this.pack(); 
        this.setLocationRelativeTo(null); 
        this.setResizable(false);
    java.net.URL keloladistributorURL = getClass().getResource("/TombolKelolaAkunDistributor.png");
    if (keloladistributorURL != null) {
        javax.swing.ImageIcon keloladistributorIcon = new javax.swing.ImageIcon(keloladistributorURL);
        java.awt.Image imgKelolaDistributor = keloladistributorIcon.getImage().getScaledInstance(300, 300, java.awt.Image.SCALE_SMOOTH);

        btnKelolaAkun.setIcon(new javax.swing.ImageIcon(imgKelolaDistributor));
        btnKelolaAkun.setText("Info Petani");

        btnKelolaAkun.setBorderPainted(false);
        btnKelolaAkun.setContentAreaFilled(false);
        btnKelolaAkun.setFocusPainted(false);
        btnKelolaAkun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKelolaAkun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKelolaAkun.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKelolaAkun.setPreferredSize(new java.awt.Dimension(220, 240));
    } else {
        System.err.println("Gambar tidak ditemukan di /resources/TombolKelolaAkunDistributor.png");
    }
    java.net.URL kelolapermintaanURL = getClass().getResource("/TombolKelolaPermintaan.png");
    if (kelolapermintaanURL != null) {
        javax.swing.ImageIcon kelolapermintaanIcon = new javax.swing.ImageIcon(kelolapermintaanURL);
        java.awt.Image imgKelolaPermintaan = kelolapermintaanIcon.getImage().getScaledInstance(300, 300, java.awt.Image.SCALE_SMOOTH);

        btnKelolaPermintaan.setIcon(new javax.swing.ImageIcon(imgKelolaPermintaan));
        btnKelolaPermintaan.setText("Info Petani");

        btnKelolaPermintaan.setBorderPainted(false);
        btnKelolaPermintaan.setContentAreaFilled(false);
        btnKelolaPermintaan.setFocusPainted(false);
        btnKelolaPermintaan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKelolaPermintaan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKelolaPermintaan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKelolaPermintaan.setPreferredSize(new java.awt.Dimension(220, 240));
    } else {
        System.err.println("Gambar tidak ditemukan di /resources/TombolKelolaPermintaan.png");
    }
    java.net.URL imgURL = getClass().getResource("/KelolaDistributorBg.png");
    if (imgURL != null) {
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
        java.awt.Image img = icon.getImage().getScaledInstance(
            800, 
            500,
            java.awt.Image.SCALE_SMOOTH
        );
        lblKelolaPanenBg.setIcon(new javax.swing.ImageIcon(img));
    } else {
        System.err.println("Gambar tidak ditemukan di /resources/KelolaDistributorBg.png");
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnKelolaAkun = new javax.swing.JButton();
        btnKelolaPermintaan = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        lblKelolaPanenBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        btnKelolaAkun.setText("Kelola Akun");
        btnKelolaAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaAkunActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaAkun);
        btnKelolaAkun.setBounds(180, 160, 200, 210);

        btnKelolaPermintaan.setText("Kelola Permintaan");
        btnKelolaPermintaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaPermintaanActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaPermintaan);
        btnKelolaPermintaan.setBounds(390, 160, 200, 210);

        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(0, 102, 0));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali);
        btnKembali.setBounds(650, 40, 90, 30);

        lblKelolaPanenBg.setText("jLabel1");
        jPanel1.add(lblKelolaPanenBg);
        lblKelolaPanenBg.setBounds(0, 0, 800, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        MenuAdmin petani = new MenuAdmin();
        petani.setVisible(true);
        this.dispose();           
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnKelolaAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaAkunActionPerformed
        KelolaAkunDistributor kelolaakun = new KelolaAkunDistributor();
        kelolaakun.setVisible(true);
        this.dispose();         
    }//GEN-LAST:event_btnKelolaAkunActionPerformed

    private void btnKelolaPermintaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaPermintaanActionPerformed
        KelolaPermintaan kelolaakun = new KelolaPermintaan();
        kelolaakun.setVisible(true);
        this.dispose();   
    }//GEN-LAST:event_btnKelolaPermintaanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuKelolaDistributor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKelolaAkun;
    private javax.swing.JButton btnKelolaPermintaan;
    private javax.swing.JButton btnKembali;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblKelolaPanenBg;
    // End of variables declaration//GEN-END:variables
}
