/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author Asus TUF
 */
public class MenuAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuAdmin.class.getName());

    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
        this.pack(); 
        this.setLocationRelativeTo(null); 
        this.setResizable(false);

    java.net.URL imgURL = getClass().getResource("/MenuAdminBg.png");
    if (imgURL != null) {
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
        java.awt.Image img = icon.getImage().getScaledInstance(
            800, 
            500,
            java.awt.Image.SCALE_SMOOTH
        );
        lblAdminBg.setIcon(new javax.swing.ImageIcon(img));
    } else {
        System.err.println("Gambar tidak ditemukan di /resources/MenuAdminBg.png");
    }

    java.net.URL kelolapetaniURL = getClass().getResource("/TombolKelolaPetani.png");
    if (kelolapetaniURL != null) {
        javax.swing.ImageIcon kelolapetaniIcon = new javax.swing.ImageIcon(kelolapetaniURL);
        java.awt.Image imgKelolaPetani = kelolapetaniIcon.getImage().getScaledInstance(300, 300, java.awt.Image.SCALE_SMOOTH);

        btnKelolaPetani.setIcon(new javax.swing.ImageIcon(imgKelolaPetani));
        btnKelolaPetani.setText("Kelola Petani");

        btnKelolaPetani.setBorderPainted(false);
        btnKelolaPetani.setContentAreaFilled(false);
        btnKelolaPetani.setFocusPainted(false);
        btnKelolaPetani.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKelolaPetani.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKelolaPetani.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKelolaPetani.setPreferredSize(new java.awt.Dimension(220, 240));
    } else {
        System.err.println("Gambar tidak ditemukan di /resources/TombolKelolaPetani.png");
    }

    java.net.URL keloladistributorURL = getClass().getResource("/TombolKelolaDistributor.png");
    if (keloladistributorURL != null) {
        javax.swing.ImageIcon keloladistributorIcon = new javax.swing.ImageIcon(keloladistributorURL);
        java.awt.Image imgKelolaDistributor = keloladistributorIcon.getImage().getScaledInstance(300, 300, java.awt.Image.SCALE_SMOOTH);

        btnKelolaDistributor.setIcon(new javax.swing.ImageIcon(imgKelolaDistributor));
        btnKelolaDistributor.setText("Info Petani");

        btnKelolaDistributor.setBorderPainted(false);
        btnKelolaDistributor.setContentAreaFilled(false);
        btnKelolaDistributor.setFocusPainted(false);
        btnKelolaDistributor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKelolaDistributor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKelolaDistributor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKelolaDistributor.setPreferredSize(new java.awt.Dimension(220, 240));
    } else {
        System.err.println("Gambar tidak ditemukan di /resources/TombolKelolaDistributor.png");
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnKelolaDistributor = new javax.swing.JButton();
        btnKelolaPetani = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        lblAdminBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        btnKelolaDistributor.setText("Kelola Distributor");
        btnKelolaDistributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaDistributorActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaDistributor);
        btnKelolaDistributor.setBounds(400, 180, 230, 220);

        btnKelolaPetani.setText("Kelola Petani");
        btnKelolaPetani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaPetaniActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaPetani);
        btnKelolaPetani.setBounds(170, 180, 230, 220);

        btnKeluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(0, 102, 0));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnKeluar);
        btnKeluar.setBounds(660, 40, 90, 30);

        lblAdminBg.setText("jLabel1");
        jPanel1.add(lblAdminBg);
        lblAdminBg.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKelolaDistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaDistributorActionPerformed
        MenuKelolaDistributor distributor = new MenuKelolaDistributor();
        distributor.setVisible(true);
        this.dispose();      
    }//GEN-LAST:event_btnKelolaDistributorActionPerformed

    private void btnKelolaPetaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaPetaniActionPerformed
        MenuKelolaPetani kelolapetani = new MenuKelolaPetani();
        kelolapetani.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_btnKelolaPetaniActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
    int confirm = JOptionPane.showConfirmDialog(
        this,
        "Apakah Anda yakin ingin keluar?",
        "Konfirmasi Keluar",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE
    );

    if (confirm == JOptionPane.YES_OPTION) {
        new DashboardLogin().setVisible(true);
        this.dispose();
    } 
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKelolaDistributor;
    private javax.swing.JButton btnKelolaPetani;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAdminBg;
    // End of variables declaration//GEN-END:variables
}
