/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Asus TUF
 */

import Model.Permintaan;
import Session.UserSession;
import java.util.List;
import javax.swing.JOptionPane;

public class PermintaanDistributorForm extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PermintaanDistributorForm.class.getName());
    private final Controller.permintaanController permintaanCtrl = new Controller.permintaanController();

    public PermintaanDistributorForm() {
        initComponents();
        this.pack(); 
        this.setLocationRelativeTo(null); 
        this.setResizable(false);
        loadDataPermintaan();
        
    java.net.URL imgURL = getClass().getResource("/BuatPermintaanDistributorBg.png");
    if (imgURL != null) {
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
        java.awt.Image img = icon.getImage().getScaledInstance(
            800, 
            500, 
            java.awt.Image.SCALE_SMOOTH
        );
        lblPermintaanDistributorBg.setIcon(new javax.swing.ImageIcon(img));
    } else {
        System.err.println("Gambar tidak ditemukan di /resources/BuatPermintaanDistributorBg.png");
    }
    }
    
    private void loadDataPermintaan() {
        List<Object[]> data = permintaanCtrl.permintaanForDistributor(); // <-- ambil semua permintaan

        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.addColumn("Nama Distributor");
        model.addColumn("Nama Usaha");
        model.addColumn("Jumlah Permintaan (Kg)");
        model.addColumn("Status");
        model.addColumn("Tanggal Permintaan");

        for (Object[] row : data) {

            model.addRow(new Object[]{
                row[0], 
                row[1], 
                row[2], 
                row[3], 
                row[4] 
            });
        }

        tblHasilPanen.setModel(model);
    }

    private void tambahPermintaan() {
        try {
            String inputJumlah = txtJumlah.getText().trim();
            if (inputJumlah.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Masukkan jumlah permintaan terlebih dahulu!");
                return;
            }

            int jumlah = Integer.parseInt(inputJumlah); 
            String satuan = cmbSatuan.getSelectedItem().toString();

            if (satuan.equalsIgnoreCase("Ton")) {
                jumlah = jumlah * 1000;
            }

            String idDistributorLogin = UserSession.getIdUser();

            Permintaan p = new Permintaan();
            p.setIdPermintaan(Controller.generateID.permintaan());
            p.setJumlahPermintaan(jumlah);
            p.setIdPanen("PAN01"); 
            p.setIdDistributor(idDistributorLogin);
            p.setIdAdmin("ADM01"); 
            p.setStatus("menunggu");

            if (permintaanCtrl.tambahPermintaan(p)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Permintaan berhasil ditambahkan!");
                loadDataPermintaan(); 
                txtJumlah.setText("");
                cmbSatuan.setSelectedIndex(0);

            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal menambahkan permintaan!");
            }

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Jumlah harus berupa angka!");
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + ex.getMessage());
            ex.printStackTrace();
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHasil = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        lblJumlah = new javax.swing.JLabel();
        cmbSatuan = new javax.swing.JComboBox<>();
        btnPerbarui = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHasilPanen = new javax.swing.JTable();
        lblPermintaanDistributorBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        lblHasil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHasil.setForeground(new java.awt.Color(255, 255, 255));
        lblHasil.setText("Satuan");
        jPanel1.add(lblHasil);
        lblHasil.setBounds(460, 140, 90, 20);
        jPanel1.add(txtJumlah);
        txtJumlah.setBounds(110, 160, 320, 40);

        lblJumlah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJumlah.setForeground(new java.awt.Color(255, 255, 255));
        lblJumlah.setText("Jumlah Permintaan ");
        jPanel1.add(lblJumlah);
        lblJumlah.setBounds(110, 140, 290, 20);

        cmbSatuan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbSatuan.setForeground(new java.awt.Color(0, 102, 0));
        cmbSatuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kg", "Ton" }));
        jPanel1.add(cmbSatuan);
        cmbSatuan.setBounds(460, 160, 110, 40);

        btnPerbarui.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPerbarui.setForeground(new java.awt.Color(0, 102, 0));
        btnPerbarui.setText("Perbarui");
        btnPerbarui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerbaruiActionPerformed(evt);
            }
        });
        jPanel1.add(btnPerbarui);
        btnPerbarui.setBounds(80, 390, 100, 30);

        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(0, 102, 0));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali);
        btnKembali.setBounds(640, 40, 100, 40);

        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(0, 102, 0));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambah);
        btnTambah.setBounds(600, 160, 100, 40);

        tblHasilPanen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id_permintaan", "jumlah_permintaan", "id_panen", "id_distributor", "id_admin", "status", "tanggal_permintaan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHasilPanen);
        if (tblHasilPanen.getColumnModel().getColumnCount() > 0) {
            tblHasilPanen.getColumnModel().getColumn(0).setResizable(false);
            tblHasilPanen.getColumnModel().getColumn(1).setResizable(false);
            tblHasilPanen.getColumnModel().getColumn(2).setResizable(false);
            tblHasilPanen.getColumnModel().getColumn(3).setResizable(false);
            tblHasilPanen.getColumnModel().getColumn(4).setResizable(false);
            tblHasilPanen.getColumnModel().getColumn(5).setResizable(false);
            tblHasilPanen.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(80, 240, 650, 150);

        lblPermintaanDistributorBg.setText("jLabel3");
        lblPermintaanDistributorBg.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.add(lblPermintaanDistributorBg);
        lblPermintaanDistributorBg.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPerbaruiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerbaruiActionPerformed
        loadDataPermintaan();
        JOptionPane.showMessageDialog(this, "Tabel diperbarui dengan data terbaru!");
    }//GEN-LAST:event_btnPerbaruiActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        MenuDistributor distributor = new MenuDistributor();
        distributor.setVisible(true);
        this.dispose();         
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        tambahPermintaan();// TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PermintaanDistributorForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnPerbarui;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cmbSatuan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JLabel lblPermintaanDistributorBg;
    private javax.swing.JTable tblHasilPanen;
    private javax.swing.JTextField txtJumlah;
    // End of variables declaration//GEN-END:variables
}
