/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.permintaanController;
import Model.Permintaan;
import Session.UserSession;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Asus TUF
 */
public class PermintaanPetaniForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PermintaanPetaniForm.class.getName());
    private final permintaanController controller = new permintaanController();
    private final String idUser = UserSession.getIdUser();
  
    public PermintaanPetaniForm() {
        initComponents();
        this.pack(); 
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        tampilkanStokGudang();
        loadTablePermintaan(); 
        setupTableClickListener();
        
        java.net.URL imgURL = getClass().getResource("/PermintaanPetaniBg.png");
        if (imgURL != null) {
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
            java.awt.Image img = icon.getImage().getScaledInstance(800, 500, java.awt.Image.SCALE_SMOOTH);
            lblPermintaanBg.setIcon(new javax.swing.ImageIcon(img));
        } else {
            System.err.println("Gambar tidak ditemukan di /resources/PermintaanPetaniBg.png");
        }
    }
private void loadTablePermintaan() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Permintaan");
    model.addColumn("Nama Usaha");
    model.addColumn("No Telepon");
    model.addColumn("Wilayah Pasar");
    model.addColumn("Jumlah Permintaan (Kg)");
    model.addColumn("Status");
    model.addColumn("Tanggal Permintaan");

    List<Object[]> data = controller.permintaanForPetani();
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");

    for (Object[] row : data) {
        String idPermintaan = (String) row[0];
        String nama = (String) row[1];
        String telp = (String) row[2];
        String wilayah = (String) row[3];
        Integer jumlah = (Integer) row[4];
        String status = (String) row[5];
        java.util.Date tgl = (java.util.Date) row[6];

        if (status != null && status.equalsIgnoreCase("dipenuhi")) {
            continue; 
        }
        model.addRow(new Object[]{idPermintaan, nama, telp, wilayah, jumlah, status, sdf.format(tgl)});
    }
    tblPermintaan.setModel(model);
}

    private void tampilkanStokGudang() {
        try (org.hibernate.Session session = Database.Koneksi.getInstance().getSession()) {
            session.clear(); 

            Database.hasilPanenService panenService = new Database.hasilPanenService();
            int stokTerbaru = panenService.getStokTerakhirByPetani(idUser);

            lblStok.setText(stokTerbaru + " Kg");
            System.out.println("[REAL-TIME] Stok terbaru user " + idUser + ": " + stokTerbaru + " Kg");

        } catch (Exception e) {
            e.printStackTrace();
            lblStok.setText("Gagal ambil data");
        }
    }

    private void setupTableClickListener() {
        tblPermintaan.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int row = tblPermintaan.getSelectedRow();
            if (row >= 0) {
                String idPermintaan = tblPermintaan.getValueAt(row, 0).toString();
                String status = tblPermintaan.getValueAt(row, 2).toString();

                txtPermintan.setText(idPermintaan);
                cmbStatus.setSelectedItem(capitalize(status));
            }
        }
        });
    }
    
    private String capitalize(String text) {
        if (text == null || text.isEmpty()) return text;
        return text.substring(0, 1).toUpperCase() + text.substring(1).toLowerCase();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblIDPermintaan = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        btnPerbarui = new javax.swing.JButton();
        JStok = new javax.swing.JPanel();
        lblStok = new javax.swing.JLabel();
        txtPermintan = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JComboBox<>();
        lblStatus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPermintaan = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        lblIDPermintaan1 = new javax.swing.JLabel();
        lblPermintaanBg = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("HASIL PANEN");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        lblIDPermintaan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIDPermintaan.setForeground(new java.awt.Color(255, 255, 255));
        lblIDPermintaan.setText("Stok Gudang");
        jPanel1.add(lblIDPermintaan);
        lblIDPermintaan.setBounds(100, 170, 190, 20);

        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(0, 102, 0));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali);
        btnKembali.setBounds(660, 40, 90, 40);

        btnPerbarui.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPerbarui.setForeground(new java.awt.Color(0, 102, 0));
        btnPerbarui.setText("Perbarui");
        btnPerbarui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerbaruiActionPerformed(evt);
            }
        });
        jPanel1.add(btnPerbarui);
        btnPerbarui.setBounds(70, 420, 110, 30);

        JStok.setBackground(new java.awt.Color(255, 255, 255));
        JStok.setToolTipText("0");

        lblStok.setText("0 Kg");

        javax.swing.GroupLayout JStokLayout = new javax.swing.GroupLayout(JStok);
        JStok.setLayout(JStokLayout);
        JStokLayout.setHorizontalGroup(
            JStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JStokLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblStok, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        JStokLayout.setVerticalGroup(
            JStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JStokLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblStok)
                .addContainerGap())
        );

        jPanel1.add(JStok);
        JStok.setBounds(100, 190, 150, 30);

        txtPermintan.setBorder(null);
        txtPermintan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPermintanActionPerformed(evt);
            }
        });
        jPanel1.add(txtPermintan);
        txtPermintan.setBounds(100, 130, 270, 40);

        cmbStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbStatus.setForeground(new java.awt.Color(0, 102, 0));
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menunggu", "Disetujui", "Dipenuhi" }));
        cmbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusActionPerformed(evt);
            }
        });
        jPanel1.add(cmbStatus);
        cmbStatus.setBounds(390, 130, 180, 40);

        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblStatus.setText("Status");
        jPanel1.add(lblStatus);
        lblStatus.setBounds(390, 110, 190, 20);

        tblPermintaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id_permintaan", "jumlah_permintaan", "id_panen", "id_distributor", "id_admin", "status", "tanggal_permintaan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPermintaan);
        if (tblPermintaan.getColumnModel().getColumnCount() > 0) {
            tblPermintaan.getColumnModel().getColumn(0).setResizable(false);
            tblPermintaan.getColumnModel().getColumn(1).setResizable(false);
            tblPermintaan.getColumnModel().getColumn(2).setResizable(false);
            tblPermintaan.getColumnModel().getColumn(3).setResizable(false);
            tblPermintaan.getColumnModel().getColumn(4).setResizable(false);
            tblPermintaan.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 260, 660, 160);

        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(0, 102, 0));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimpan);
        btnSimpan.setBounds(600, 130, 90, 40);

        lblIDPermintaan1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIDPermintaan1.setForeground(new java.awt.Color(255, 255, 255));
        lblIDPermintaan1.setText("ID Permintaan");
        jPanel1.add(lblIDPermintaan1);
        lblIDPermintaan1.setBounds(100, 110, 190, 20);

        lblPermintaanBg.setText("jLabel3");
        jPanel1.add(lblPermintaanBg);
        lblPermintaanBg.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatusActionPerformed

    private void txtPermintanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPermintanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPermintanActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        new MenuPetani().setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnPerbaruiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerbaruiActionPerformed
        loadTablePermintaan();
        tampilkanStokGudang();
        try {
            Controller.hasilPanenController panenController = new Controller.hasilPanenController();
            Database.hasilPanenService panenService = new Database.hasilPanenService();

            int stokTerbaru = panenService.getStokTerakhirByPetani(idUser);

            java.util.List<Model.hasilPanen> daftarPanen = panenController.getPanenByPetani(idUser);

            if (!daftarPanen.isEmpty()) {
                Model.hasilPanen panenTerakhir = daftarPanen.get(daftarPanen.size() - 1);

                if (panenTerakhir.getStokGudang() != stokTerbaru) {
                    panenTerakhir.setStokGudang(stokTerbaru);
                    panenController.update(panenTerakhir);
                    System.out.println("[INFO] Sinkronisasi stok gudang: " + stokTerbaru + " Kg");
                }
            }
            JOptionPane.showMessageDialog(this, "Tabel dan stok gudang diperbarui!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal memperbarui stok gudang: " + e.getMessage(),
                                          "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnPerbaruiActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
    String idPermintaan = txtPermintan.getText().trim();
    String statusBaru = cmbStatus.getSelectedItem().toString();

    if (idPermintaan.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Pilih permintaan yang ingin diubah terlebih dahulu!",
            "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int selectedRow = tblPermintaan.getSelectedRow();
    if (selectedRow >= 0) {
        String statusSekarang = tblPermintaan.getValueAt(selectedRow, 5).toString();

        if (statusSekarang.equalsIgnoreCase("dipenuhi")) {
            JOptionPane.showMessageDialog(this,
                "Status tidak dapat diubah lagi!",
                "Akses Ditolak",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (statusSekarang.equalsIgnoreCase("disetujui") &&
            !statusBaru.equalsIgnoreCase("dipenuhi")) {

            JOptionPane.showMessageDialog(this,
                "Status tidak bisa diubah!",
                "Akses Ditolak",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
    }

    int confirm = JOptionPane.showConfirmDialog(
        this,
        "Apakah Anda yakin ingin mengubah status permintaan " + idPermintaan +
        " menjadi \"" + statusBaru + "\"?",
        "Konfirmasi Ubah Status",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE
    );

    if (confirm == JOptionPane.YES_OPTION) {
        boolean success = controller.ubahStatus(idPermintaan, statusBaru);

        if (success) {
            JOptionPane.showMessageDialog(this,
                "Status berhasil diperbarui!");
            loadTablePermintaan();
            tampilkanStokGudang();
        } else {
            JOptionPane.showMessageDialog(this,
                "Gagal memperbarui status!",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this,
            "Perubahan status dibatalkan.",
            "Dibatalkan", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PermintaanPetaniForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JStok;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnPerbarui;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIDPermintaan;
    private javax.swing.JLabel lblIDPermintaan1;
    private javax.swing.JLabel lblPermintaanBg;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStok;
    private javax.swing.JTable tblPermintaan;
    private javax.swing.JTextField txtPermintan;
    // End of variables declaration//GEN-END:variables
}
