/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;


/**
 *
 * @author Asus TUF
 */
public class PetaniForm extends javax.swing.JFrame {  
    private String idPetani;
    
    public PetaniForm(String idPetani) {
        initComponents();
        this.pack(); 
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.idPetani = idPetani;
        
        System.out.println("[DEBUG] PetaniForm dibuka untuk ID: " + idPetani);
        java.net.URL imgURL = getClass().getResource("/PetaniBg.png");
        if (imgURL != null) {
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
            java.awt.Image img = icon.getImage().getScaledInstance(
                800, 
                500, 
                java.awt.Image.SCALE_SMOOTH
            );
            lblPetaniBg.setIcon(new javax.swing.ImageIcon(img));
        } else {
            System.err.println("Gambar tidak ditemukan di /resources/PetaniBg.png");
        }
    }     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNoTelp = new javax.swing.JTextField();
        lblNoTelp = new javax.swing.JLabel();
        txtNamaSawah = new javax.swing.JTextField();
        lblNamaSawah = new javax.swing.JLabel();
        txtLuasLahan = new javax.swing.JTextField();
        lblLuasLahan = new javax.swing.JLabel();
        txtLokasi = new javax.swing.JTextField();
        lblLokasi = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        lblPetaniBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        txtNoTelp.setColumns(15);
        txtNoTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoTelpActionPerformed(evt);
            }
        });
        jPanel1.add(txtNoTelp);
        txtNoTelp.setBounds(420, 130, 281, 34);

        lblNoTelp.setBackground(new java.awt.Color(255, 255, 255));
        lblNoTelp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNoTelp.setForeground(new java.awt.Color(255, 255, 255));
        lblNoTelp.setText("No. Telp");
        jPanel1.add(lblNoTelp);
        lblNoTelp.setBounds(420, 100, 69, 20);

        txtNamaSawah.setColumns(15);
        jPanel1.add(txtNamaSawah);
        txtNamaSawah.setBounds(420, 200, 281, 34);

        lblNamaSawah.setBackground(new java.awt.Color(255, 255, 255));
        lblNamaSawah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNamaSawah.setForeground(new java.awt.Color(255, 255, 255));
        lblNamaSawah.setText("Nama Sawah");
        jPanel1.add(lblNamaSawah);
        lblNamaSawah.setBounds(420, 170, 97, 20);

        txtLuasLahan.setColumns(15);
        jPanel1.add(txtLuasLahan);
        txtLuasLahan.setBounds(420, 270, 281, 34);

        lblLuasLahan.setBackground(new java.awt.Color(255, 255, 255));
        lblLuasLahan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLuasLahan.setForeground(new java.awt.Color(255, 255, 255));
        lblLuasLahan.setText("Luas Lahan (m2)");
        jPanel1.add(lblLuasLahan);
        lblLuasLahan.setBounds(420, 240, 97, 20);

        txtLokasi.setColumns(15);
        jPanel1.add(txtLokasi);
        txtLokasi.setBounds(420, 340, 281, 34);

        lblLokasi.setBackground(new java.awt.Color(255, 255, 255));
        lblLokasi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLokasi.setForeground(new java.awt.Color(255, 255, 255));
        lblLokasi.setText("Lokasi");
        jPanel1.add(lblLokasi);
        lblLokasi.setBounds(420, 310, 97, 20);

        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(0, 102, 0));
        btnKembali.setText("Kembali");
        btnKembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali);
        btnKembali.setBounds(460, 390, 90, 31);

        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(0, 102, 0));
        btnSimpan.setText("Simpan");
        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimpan);
        btnSimpan.setBounds(560, 390, 84, 31);

        lblPetaniBg.setText("jLabel1");
        jPanel1.add(lblPetaniBg);
        lblPetaniBg.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        RegisterForm register = new RegisterForm();
        register.setVisible(true);
        this.dispose();             
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
    try {
        String noTelp = txtNoTelp.getText().trim();
        String namaSawah = txtNamaSawah.getText().trim();
        String luasLahanStr = txtLuasLahan.getText().trim();
        String lokasi = txtLokasi.getText().trim();

        Controller.petaniController controller = new Controller.petaniController();
        boolean success = controller.updateDataPetani(idPetani, noTelp, namaSawah, lokasi, luasLahanStr);

        if (success) {
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
            new LoginForm().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data! Pastikan semua input benar.");
        }

    } catch (HeadlessException e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtNoTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoTelpActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

//        /* Create and display the form */
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLokasi;
    private javax.swing.JLabel lblLuasLahan;
    private javax.swing.JLabel lblNamaSawah;
    private javax.swing.JLabel lblNoTelp;
    private javax.swing.JLabel lblPetaniBg;
    private javax.swing.JTextField txtLokasi;
    private javax.swing.JTextField txtLuasLahan;
    private javax.swing.JTextField txtNamaSawah;
    private javax.swing.JTextField txtNoTelp;
    // End of variables declaration//GEN-END:variables
}
