/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Asus TUF
 */

import Controller.RegisterController;
import javax.swing.JOptionPane;

public class RegisterForm extends javax.swing.JFrame {  
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterForm.class.getName());
    
    public RegisterForm() {
        initComponents();
        this.pack(); 
        this.setLocationRelativeTo(null); 
        this.setResizable(false);
    java.net.URL imgURL = getClass().getResource("/RegistrasiBg.png");
    if (imgURL != null) {
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
        java.awt.Image img = icon.getImage().getScaledInstance(
            800, 
            500,
            java.awt.Image.SCALE_SMOOTH
        );
        lblRegisterBg.setIcon(new javax.swing.ImageIcon(img));
    } else {
        System.err.println("Gambar tidak ditemukan di /resources/RegisterBg.png");
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblNama = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox<>();
        lblRole = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        btnDaftar = new javax.swing.JButton();
        jPassword = new javax.swing.JPasswordField();
        lblRegisterBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel3.setLayout(null);

        lblNama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNama.setForeground(new java.awt.Color(255, 255, 255));
        lblNama.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNama.setText("Nama Lengkap");
        jPanel3.add(lblNama);
        lblNama.setBounds(420, 110, 110, 20);

        txtNama.setColumns(15);
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        jPanel3.add(txtNama);
        txtNama.setBounds(420, 130, 280, 34);

        txtUsername.setColumns(15);
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        jPanel3.add(txtUsername);
        txtUsername.setBounds(420, 190, 280, 34);

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsername.setText("Username");
        jPanel3.add(lblUsername);
        lblUsername.setBounds(420, 170, 110, 20);

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPassword.setText("Password");
        jPanel3.add(lblPassword);
        lblPassword.setBounds(420, 230, 110, 20);

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Petani", "Distributor" }));
        jPanel3.add(cmbRole);
        cmbRole.setBounds(420, 310, 280, 31);

        lblRole.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRole.setForeground(new java.awt.Color(255, 255, 255));
        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRole.setText("Role");
        jPanel3.add(lblRole);
        lblRole.setBounds(420, 290, 110, 20);

        lblLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(0, 102, 0));
        lblLogin.setText("Sudah punya akun? Login");
        lblLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
        });
        jPanel3.add(lblLogin);
        lblLogin.setBounds(90, 160, 150, 16);

        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(0, 102, 0));
        btnKembali.setText("Kembali");
        btnKembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel3.add(btnKembali);
        btnKembali.setBounds(460, 360, 90, 30);

        btnDaftar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDaftar.setForeground(new java.awt.Color(0, 102, 0));
        btnDaftar.setText("Daftar");
        btnDaftar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarActionPerformed(evt);
            }
        });
        jPanel3.add(btnDaftar);
        btnDaftar.setBounds(560, 360, 80, 30);

        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        jPanel3.add(jPassword);
        jPassword.setBounds(420, 250, 280, 30);

        lblRegisterBg.setText("jLabel1");
        jPanel3.add(lblRegisterBg);
        lblRegisterBg.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        DashboardLogin register = new DashboardLogin();
        register.setVisible(true);
        this.dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
    
    RegisterController regCtrl = new RegisterController();    
    String nama = txtNama.getText().trim();
    String username = txtUsername.getText().trim();
    String password = new String(jPassword.getPassword()).trim();
    String role = cmbRole.getSelectedItem().toString();

    String result = regCtrl.registerUser(nama, username, password, role);

    if (result.startsWith("success_petani")) {
        String idPetani = result.split(":")[1];
        JOptionPane.showMessageDialog(this, "Registrasi Petani berhasil!");
        try {
            new view.PetaniForm(idPetani).setVisible(true);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal membuka PetaniForm: " + e.getMessage());
        }
        return;
    }

    if (result.startsWith("success_distributor")) {
        String idDistributor = result.split(":")[1];
        JOptionPane.showMessageDialog(this, "Registrasi Distributor berhasil!");
        try {
            Controller.distributorController ctrl = new Controller.distributorController();
            new view.DistributorForm(idDistributor, ctrl).setVisible(true);

            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal membuka DistributorForm: " + e.getMessage());
        }
        return;
    }

    switch (result) {
        case "empty_name" ->
            JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong!");
        case "empty_username" ->
            JOptionPane.showMessageDialog(this, "Username tidak boleh kosong!");
        case "empty_password" ->
            JOptionPane.showMessageDialog(this, "Password tidak boleh kosong!");
        case "username_exists" ->
            JOptionPane.showMessageDialog(this, "Username sudah terdaftar!");
        case "invalid_role" ->
            JOptionPane.showMessageDialog(this, "Role tidak valid!");
        case "fail" ->
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data ke database!");
        default ->
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan sistem!");
    }
    }//GEN-LAST:event_btnDaftarActionPerformed

    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseClicked
        new view.LoginForm().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_lblLoginMouseClicked

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegisterForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDaftar;
    private javax.swing.JButton btnKembali;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRegisterBg;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
